terafoundation:
  environment: "development"
  log_level: debug
  connectors:
    elasticsearch-next:
      default:
        node:
          - "http://elasticsearch.services-dev1:9200"
    kafka:
      default:
        brokers:
          - "cpkafka.services-dev1:9092"
    s3:
      default:
        endpoint: "http://minio.services-dev1:9000"
        accessKeyId: "minioadmin"
        secretAccessKey: "minioadmin"
        forcePathStyle: true
        sslEnabled: false
        region: "us-east-1"
teraslice:
  worker_disconnect_timeout: 60000
  node_disconnect_timeout: 60000
  slicer_timeout: 60000
  shutdown_timeout: 30000
  assets_directory: "/app/assets/"
  autoload_directory: "/app/autoload"
  cluster_manager_type: "kubernetes"
  master: false
  master_hostname: "teraslice-master"
  kubernetes_image: "" # set dynamically w/ scripts/src/helpers/config.ts NODE_VERSION: teraslice-workspace:e2e-nodev${NODE_VERSION}
  kubernetes_namespace: "ts-dev1"
  kubernetes_overrides_enabled: true
  kubernetes_priority_class_name: "high-priority"
  name: "ts-dev1"
  cpu: 1
  memory: 536870912
