/** Declaration file generated by dts-gen */

export function getFixturePath(cwd: string, ...fileParts: string[]): Promise<string>;
export function getFixturePathSync(cwd: string, ...fileParts: string[]): string;
export function createTempDir(): Promise<string>;
export function createTempDirSync(): string;
export function copyDir(src: string, dest: string): Promise<void>;
export function copyDirIntoTempDir(src: string): Promise<string>;
export function copyFixtureIntoTempDir(cwd: string, fixturePath: string): Promise<string>;
export function cleanupTempDirs(): Promise<void>;
