const {
    TEST_INDEX_PREFIX = 'teratest_',
    ELASTICSEARCH_HOST = 'http://localhost:9200',
    ELASTICSEARCH_VERSION = '6.8.6',
    OPENSEARCH_PORT = '49210',
    OPENSEARCH_HOSTNAME = `http://localhost:${OPENSEARCH_PORT}`,
    OPENSEARCH_USER = 'admin',
    OPENSEARCH_PASSWORD = 'admin',
    OPENSEARCH_VERSION = '1.3.0',
    OPENSEARCH_HOST = `http://${OPENSEARCH_USER}:${OPENSEARCH_PASSWORD}@${OPENSEARCH_HOSTNAME}`,
    OPENSEARCH_SSL_HOST = `https://${OPENSEARCH_HOSTNAME}:${OPENSEARCH_PORT}`,
    RESTRAINED_OPENSEARCH_PORT = process.env.RESTRAINED_OPENSEARCH_PORT || '49206',
    RESTRAINED_OPENSEARCH_HOST = `http://${OPENSEARCH_USER}:${OPENSEARCH_PASSWORD}@localhost:${RESTRAINED_OPENSEARCH_PORT}`,
} = process.env;

export {
    TEST_INDEX_PREFIX,
    ELASTICSEARCH_HOST,
    ELASTICSEARCH_VERSION,
    OPENSEARCH_HOST,
    OPENSEARCH_SSL_HOST,
    OPENSEARCH_VERSION,
    RESTRAINED_OPENSEARCH_HOST,
    OPENSEARCH_USER,
    OPENSEARCH_PASSWORD
};
