const {
    TEST_INDEX_PREFIX = 'teratest_',
    ELASTICSEARCH_HOST = 'http://localhost:9200',
    ELASTICSEARCH_API_VERSION = '6.5',
    ELASTICSEARCH_VERSION = '6.8.6'
} = process.env;

export {
    TEST_INDEX_PREFIX,
    ELASTICSEARCH_HOST,
    ELASTICSEARCH_API_VERSION,
    ELASTICSEARCH_VERSION
};
