packages:
  - e2e
  - packages/*

onlyBuiltDependencies:
  - '@confluentinc/kafka-javascript'
  - '@swc/core'
  - dtrace-provider
  - esbuild
  - event-loop-stats
  - gc-stats
  - unrs-resolver
  - xlucene-parser

publicHoistPattern:
  - "terafoundation_kafka_connector"
  - "@terascope/scripts"