terafoundation:
    environment: 'development'
    log_level: info
    connectors:
        # ***********************
        # Elastic Search Configuration
        # ***********************
        elasticsearch:
            default:
                host:
                    - "elasticsearch:49200"

teraslice:
    worker_disconnect_timeout: 120000
    node_disconnect_timeout: 120000
    slicer_timeout: 60000
    shutdown_timeout: 30000
    assets_directory: '/tmp/'
    workers: 5
    master: true
    master_hostname: "127.0.0.1"
    port: 45678
    name: "teracluster"
