terafoundation:
    environment: 'development'
    log_level: debug
    connectors:
        # ***********************
        # Elastic Search Configuration
        # ***********************
        elasticsearch:
            default:
                host:
                    - '$ELASTICSEARCH_URL'
                requestTimeout: 60000
                deadTimeout: 45000
                sniffOnStart: false
                sniffOnConnectionFault: false
                suggestCompression: false

        # ***********************
        # Kafka Configuration
        # ***********************
        kafka:
            default:
                brokers:
                    - '$KAFKA_BROKERS'

teraslice:
    worker_disconnect_timeout: 120000
    node_disconnect_timeout: 120000
    slicer_timeout: 180000
    shutdown_timeout: 30000
    action_timeout: 30000
    assets_directory: '/app/assets'
    autoload_directory: '/app/autoload'
    workers: 12
    master: true
    master_hostname: '127.0.0.1'
    port: 45678
    name: '$CLUSTER_NAME'
    index_settings:
        analytics:
            number_of_shards: 1
            number_of_replicas: 0
        assets:
            number_of_shards: 1
            number_of_replicas: 0
        jobs:
            number_of_shards: 1
            number_of_replicas: 0
        execution:
            number_of_shards: 1
            number_of_replicas: 0
        state:
            number_of_shards: 1
            number_of_replicas: 0
