terafoundation:
    environment: 'development'
    log_level: debug
    connectors:
        # ***********************
        # Elastic Search Configuration
        # ***********************
        elasticsearch:
            default:
                host:
                    - "elasticsearch:49200"
        # ***********************
        # Kafka Configuration
        # ***********************
        kafka:
            default:
                brokers:
                    - "kafka:49092"
teraslice:
    worker_disconnect_timeout: 120000
    node_disconnect_timeout: 120000
    slicer_timeout: 180000
    shutdown_timeout: 30000
    action_timeout: 30000
    assets_directory: '/app/assets'
    autoload_directory: '/app/autoload'
    workers: 12
    master: false
    master_hostname: "teraslice-master"
    port: 45678
    name: "teracluster"
    index_settings:
        analytics:
            number_of_shards: 1
            number_of_replicas: 0
        assets:
            number_of_shards: 1
            number_of_replicas: 0
        jobs:
            number_of_shards: 1
            number_of_replicas: 0
        execution:
            number_of_shards: 1
            number_of_replicas: 0
        state:
            number_of_shards: 1
            number_of_replicas: 0
