// NOTE: This code is auto-generated by `teraslice-cli assets init --registry`
// any manual changes will be lost next time this gets auto-generated.
import exampleProcessor from './example/processor.js';
import examplePSchema from './example/schema.js';

export default {
    ASSETS: {
        example: {
            Processor: exampleProcessor,
            Schema: examplePSchema,
        },
    }
};
