// NOTE: This code is auto-generated by `teraslice-cli assets init --registry`
// any manual changes will be lost next time this gets auto-generated.

export default {
    ASSETS: {
        example: {
            Processor: require('./example/processor.js'),
            Schema: require('./example/schema.js'),
        },
    }
};
