terafoundation:
    environment: 'development'

    connectors:
        # ***********************
        # Elastic Search Configuration
        # ***********************
        elasticsearch:
            default:
                host:
                    - "elasticsearch:9200"

teraslice:
    ops_directory: '/app/source/examples/ops/'

    cluster:
        master: false
        master_hostname: "teraslice-master"
        name: "teracluster"

