/* eslint-disable */

// NOTE: This code is auto-generated by `teraslice-cli assets registry`
// any manual changes will be lost next time this gets auto-generated.

export default {
    ASSETS: {
        proc: {
            Processor: require('./proc/processor.js'),
            Schema: require('./proc/schema.js'),
            Slicer: require('./proc/slicer.js'),
            },
        proc2: {
            API: require('./proc2/api.js'),
            Fetcher: require('./proc2/fetcher.js'),
            Schema: require('./proc2/schema.js'),
            },
        }
};
