#!/usr/bin/env bash
# Creates the cluster on first run -- fsid, ceph.conf, keyrings, monmap, and the
# monitor's data store -- and then runs the monitor.
#
# Bootstrapping lives here rather than in a container of its own so the monitor
# can read its address off its own interface at runtime. That is the only reason
# this stack ever pinned a subnet: a separate bootstrap container has no way to
# know what address the monitor will end up with, so it had to be told one in
# advance, which meant fixing the network too. Now nothing is pinned and docker
# allocates whatever range is free, so the stack cannot collide with an existing
# network.
ROLE=mon
source /scripts/common.sh

MON_ID=${MON_ID:-mon0}
MON_DATA=/var/lib/ceph/mon/ceph-${MON_ID}
MON_ADDR=$(own_addr)

# Replicate only as widely as there are OSDs to replicate across. With one OSD
# and size=2 every PG sits active+undersized+degraded forever: writes still
# succeed via min_size=1, but the cluster never reaches HEALTH_OK.
OSD_COUNT=${OSD_COUNT:-1}
POOL_SIZE=$(( OSD_COUNT >= 2 ? 2 : 1 ))

mkdir -p /etc/ceph /var/lib/ceph/mon /var/lib/ceph/bootstrap-osd /var/lib/ceph/mgr

# Keep the fsid across restarts; only mint one for a genuinely new cluster.
FSID=$(awk '/^fsid/ {print $3}' "$CEPH_CONF" 2>/dev/null || true)
if [ -z "$FSID" ]; then
  FSID=$(uuidgen)
  log "creating new cluster, fsid=${FSID}"
else
  log "reusing existing cluster, fsid=${FSID}"
fi

# ceph.conf is entirely generated, so rewrite it on every start rather than
# patching it. That is what keeps mon_host correct when docker hands out a
# different address after a `down` that kept the volumes.
cat > "$CEPH_CONF" <<EOF
# Generated by scripts/mon.sh -- single-node Ceph for local testing.
# Rewritten on every monitor start. Not a production configuration.
[global]
fsid = ${FSID}
mon_initial_members = ${MON_ID}
mon_host = [v2:${MON_ADDR}:3300,v1:${MON_ADDR}:6789]

# Deliberately no public_network/cluster_network: these containers have a single
# interface, so Ceph binds to the right address on its own, and hardcoding a
# range here would put back the pinned-subnet problem this layout removes.

auth_cluster_required = cephx
auth_service_required = cephx
auth_client_required = cephx

# One host: replicate across OSDs rather than across hosts.
osd_crush_chooseleaf_type = 0
osd_pool_default_size = ${POOL_SIZE}
osd_pool_default_min_size = 1
# Deliberately no osd_pool_default_pg_num/pgp_num here: the autoscaler starts
# new pools at pg_num=1, and a pinned pgp_num above that makes every librados
# pool_create (i.e. every pool RGW creates for itself) fail with ERANGE.

# Cache ceiling per OSD. Only approached under sustained write load -- idle RSS
# is well under 100 MiB. Keeps a heavy test from ballooning inside Docker's VM.
osd_memory_target = 939524096

# Log to stderr so "docker compose logs" actually shows something. The upstream
# images default to journald, which no one is running inside these containers.
log_to_stderr = true
err_to_stderr = true
log_to_file = false
log_to_journald = false
mon_cluster_log_to_stderr = true
mon_cluster_log_to_file = false
mon_cluster_log_to_journald = false

# Warnings that are noise on a disposable single-node cluster.
mon_warn_on_insecure_global_id_reclaim = false
mon_warn_on_insecure_global_id_reclaim_allowed = false
mon_warn_on_pool_no_redundancy = false
auth_allow_insecure_global_id_reclaim = true
mon_data_avail_warn = 2
mon_data_avail_crit = 1

[mon]
mon_allow_pool_delete = true

[osd]
osd_max_pg_per_osd_hard_ratio = 10
EOF

if [ ! -f "${MON_DATA}/keyring" ]; then
  log "bootstrapping monitor at ${MON_ADDR}"

  # Monitor keyring.
  ceph-authtool --create-keyring /tmp/ceph.mon.keyring \
    --gen-key -n mon. --cap mon 'allow *'

  # Admin keyring -- this is what the toolbox and every script authenticates as.
  ceph-authtool --create-keyring /etc/ceph/ceph.client.admin.keyring \
    --gen-key -n client.admin \
    --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow *' --cap mgr 'allow *'

  # OSD bootstrap keyring.
  ceph-authtool --create-keyring /var/lib/ceph/bootstrap-osd/ceph.keyring \
    --gen-key -n client.bootstrap-osd \
    --cap mon 'profile bootstrap-osd' --cap mgr 'allow r'

  ceph-authtool /tmp/ceph.mon.keyring --import-keyring /etc/ceph/ceph.client.admin.keyring
  ceph-authtool /tmp/ceph.mon.keyring --import-keyring /var/lib/ceph/bootstrap-osd/ceph.keyring

  monmaptool --create \
    --addv "${MON_ID}" "[v2:${MON_ADDR}:3300,v1:${MON_ADDR}:6789]" \
    --fsid "${FSID}" /tmp/monmap

  mkdir -p "$MON_DATA"
  ceph-mon --mkfs -i "$MON_ID" --monmap /tmp/monmap --keyring /tmp/ceph.mon.keyring
else
  # The store already holds a monmap naming whatever address this container had
  # last time. Reconcile it before starting, or the monitor fails to bind.
  # Modify the stored map rather than creating a fresh one so the fsid and the
  # map epoch survive.
  ceph-mon -i "$MON_ID" --extract-monmap /tmp/monmap >/dev/null 2>&1 \
    || die "could not read the existing monmap from ${MON_DATA}"

  if monmaptool --print /tmp/monmap 2>/dev/null | grep -q "v1:${MON_ADDR}:6789"; then
    log "monmap already lists ${MON_ADDR}"
  else
    log "monitor address changed, rewriting monmap to ${MON_ADDR}"
    monmaptool --rm "$MON_ID" /tmp/monmap >/dev/null
    monmaptool --addv "${MON_ID}" "[v2:${MON_ADDR}:3300,v1:${MON_ADDR}:6789]" /tmp/monmap >/dev/null
    ceph-mon -i "$MON_ID" --inject-monmap /tmp/monmap
  fi
fi

fix_perms /etc/ceph /var/lib/ceph

log "starting ceph-mon id=${MON_ID} at ${MON_ADDR}"
exec ceph-mon -f -i "$MON_ID" --setuser ceph --setgroup ceph
