/** Declaration file generated by dts-gen */

export const HOST: string;

export const MAX: number;

export const MIN: number;

export function find(...args: any[]): any;

export function get(...args: any[]): any;

export function test(port: any): any;
