import {
    DataTypeFieldConfig, DataTypeFields,
    Maybe, SortOrder,
    ReadonlyDataTypeFields
} from '@terascope/types';
import { HASH_CODE_SYMBOL, md5 } from '../core-utils';
import { Data, DataValueTuple, VectorType } from './interfaces';

/**
 * An immutable typed Array class with a constrained API.
*/
export abstract class Vector<T = unknown> {
    /**
     * Make an instance of a Vector from a config
    */
    static make<R>(
        config: Readonly<DataTypeFieldConfig>,
        data: Data<R>,
        childConfig?: DataTypeFields
    ): Vector<R> {
        throw new Error(`This is overridden in the index file, ${config} ${data} ${childConfig}`);
    }

    /**
     * The type of Vector, this should only be set the specific Vector type classes.
    */
    readonly type: VectorType;

    /**
     * The field type configuration
    */
    readonly config: Readonly<DataTypeFieldConfig>;

    /**
     * A function for converting a value to an JSON spec compatible format.
     * This is specific on the vector type classes via a static method usually.
    */
    readonly valueToJSON?: ValueToJSONFn<T>;

    /**
     * When Vector is an object type, this will be the data type fields
     * for the object
    */
    readonly childConfig?: ReadonlyDataTypeFields;

    /**
     * A data type agnostic in-memory representation of the data
     * for a Vector and potential indices/unique values.
     *
     * This should be generated by the builder and
     * should NOT be mutated one created.
     *
     * @internal
    */
    readonly data: Data<T>;

    /**
     * If set to false, the Vector is not sortable
    */
    sortable = true;

    private __cachedHash?: string|undefined;

    constructor(
        /**
         * This will be set automatically by specific Vector classes
         */
        type: VectorType,
        {
            data, config, childConfig, valueToJSON,
        }: VectorOptions<T>
    ) {
        this.type = type;
        this.config = config;
        this.valueToJSON = valueToJSON;

        this.data = data;
        this.childConfig = childConfig;
    }

    * [Symbol.iterator](): IterableIterator<Maybe<T>> {
        for (const valIndex of this.data.indices) {
            const [, value] = this.data.values.get(valIndex)!;
            yield value;
        }
    }

    get [HASH_CODE_SYMBOL](): string {
        if (this.__cachedHash) return this.__cachedHash;
        return md5(this.data.indices.join());
    }

    /**
     * Returns the number items in the Vector
    */
    get size(): number {
        return this.data.indices.length;
    }

    /**
     * Gets the number distinct values in the Vector
    */
    distinct(): number {
        return this.data.values.size;
    }

    /**
     * Get value by index
    */
    get(index: number, json?: boolean): Maybe<T>|Maybe<JSONValue<T>> {
        const hash = this.data.indices[index];
        // return the hash so we can pass through undefined
        if (hash == null) return hash;

        const [, val] = this.data.values.get(hash)!;
        if (!json || !this.valueToJSON) {
            return val;
        }
        return this.valueToJSON(val as T);
    }

    /**
     * Create a new Vector with the same metadata but with different data
    */
    abstract fork(data: Data<T>): Vector<T>;

    /**
     * Create a new Vector with the range of values
    */
    slice(start?: number, end?: number): Vector<T> {
        const indices = this.data.indices.slice(start, end);
        const entries: [string|null, DataValueTuple<T>][] = [];
        for (const [hash, val] of this.data.values) {
            if (indices.includes(hash)) {
                entries.push([hash, val]);
            }
        }
        return this.fork(Object.freeze({
            values: new Map(entries),
            indices: Object.freeze(indices)
        }));
    }

    /**
     * Sort the values in a Vector and return
     * an array with the updated indices.
    */
    getSortedIndices(direction?: SortOrder): number[] {
        if (!this.sortable) {
            throw new Error(`Sorting is not supported for ${this.constructor.name}`);
        }

        const len = this.size;
        const indices: number[] = Array(len);
        const original: [number, Maybe<T>][] = Array(len);

        for (let i = 0; i < len; i++) {
            original[i] = [i, this.get(i) as Maybe<T>];
        }

        original
            .sort(([, a], [, b]) => this.compare(a, b))
            .forEach(([i], newPosition) => {
                if (direction === 'desc') {
                    indices[i] = Math.abs(newPosition - (len - 1));
                } else {
                    indices[i] = newPosition;
                }
            });

        return indices;
    }

    /**
     * Compare two different values on the Vector type.
     * This can be used for equality or sorted.
    */
    compare(a: Maybe<T>, b: Maybe<T>): -1|0|1 {
        const aVal = a as any;
        const bVal = b as any;
        if (aVal < bVal) return -1;
        if (aVal > bVal) return 1;
        return 0;
    }

    /**
     * Convert the Vector an array of values (the output is JSON compatible)
    */
    toJSON(): Maybe<JSONValue<T>>[] {
        const res: Maybe<JSONValue<T>>[] = Array(this.size);
        for (let i = 0; i < this.size; i++) {
            res[i] = this.get(i, true) as JSONValue<T>;
        }
        return res;
    }
}

/**
 * Returns true if the input is a Vector
 */
export function isVector<T>(input: unknown): input is Vector<T> {
    return input instanceof Vector;
}

/**
 * Serialize a value to a JSON compatible format (so it can be JSON stringified)
*/
export type ValueToJSONFn<T> = (value: T, thisArg?: Vector<T>) => any;

/**
 * A list of Vector Options
 */
export interface VectorOptions<T> {
    data: Data<T>;
    config: Readonly<DataTypeFieldConfig>;
    valueToJSON?: ValueToJSONFn<T>;
    childConfig?: ReadonlyDataTypeFields;
}

export type JSONValue<T> = T extends Vector<infer U> ? U[] : T;
export type MaybeJSONValue<T> = Maybe<T>|Maybe<JSONValue<T>>;
