terafoundation:
    environment: 'development'

    connectors:
        # ***********************
        # Elastic Search Configuration
        # ***********************
        elasticsearch:
            default:
                host:
                    - "elasticsearch:49200"

teraslice:
    ops_directory: '/app/source/examples/ops/'
    workers: 8
    master: true
    master_hostname: "127.0.0.1"
    port: 45678
    name: "teracluster"
