terafoundation:
    environment: 'development'
    log_level: warn
    connectors:
        # ***********************
        # Elastic Search Configuration
        # ***********************
        elasticsearch:
            default:
                host:
                    - "elasticsearch:49200"

teraslice:
    worker_disconnect_timeout: 120000
    node_disconnect_timeout: 120000
    slicer_timeout: 60000
    shutdown_timeout: 30000
    slicer_port_range: '45679:47678'
    assets_directory: '/tmp/'
    ops_directory: '/app/source/examples/ops/'
    workers: 8
    master: true
    master_hostname: "127.0.0.1"
    port: 45678
    name: "teracluster"
