kind: Cluster
name: k8s-env
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30678 # Map internal teraslice api service to host port
    hostPort: 5678
  - containerPort: 30921 # Map internal opensearch1 service to host port
    hostPort: 9200
