kind: Cluster
name: k8s-env
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.28.12@sha256:fa0e48b1e83bb8688a5724aa7eebffbd6337abd7909ad089a2700bf08c30c6ea
  extraPortMappings:
  - containerPort: 30678 # Map internal teraslice service to host port
    hostPort: 5678
  - containerPort: 30201 # Map internal opensearch1 service to host port
    hostPort: 9201
  - containerPort: 30202 # Map internal opensearch2 service to host port
    hostPort: 9200
  - containerPort: 30206 # Map internal elasticsearch6 service to host port
    hostPort: 9206
  - containerPort: 30207 # Map internal elasticsearch7 service to host port
    hostPort: 9207
  - containerPort: 30092 # Map internal kafka service to host port
    hostPort: 9092
  - containerPort: 30094 # Map external kafka service to host port
    hostPort: 9094
  - containerPort: 30084 # Map external kafka-ui service to host port
    hostPort: 8084
  - containerPort: 30900 # Map internal minio service to host port
    hostPort: 9000
  - containerPort: 30901 # Map internal minio-ui service to host port
    hostPort: 9001
  - containerPort: 30333 # Map internal chaos-mesh-ui service to host port
    hostPort: 2333
  extraMounts:
  - hostPath: ../../e2e/autoload
    containerPath: /autoload
  - hostPath: ../../e2e/helm/utility/data
    containerPath: /data

###
# Uncomment the code below for a multi-node kind cluster
# For more than 2 nodes, just copy it and  paste it again to add nodes
###
# - role: worker
#   image: kindest/node:v1.28.12@sha256:fa0e48b1e83bb8688a5724aa7eebffbd6337abd7909ad089a2700bf08c30c6ea
#   extraMounts:
#   - hostPath: ./e2e/autoload
#     containerPath: /autoload
