apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
      app.kubernetes.io/name: elasticsearch
      app.kubernetes.io/component: master
spec:
  replicas: 1
  selector:
      matchLabels:
          app.kubernetes.io/name: elasticsearch
          app.kubernetes.io/component: master
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elasticsearch
        app.kubernetes.io/component: master
    spec:
      containers:
      - name: elasticsearch
        # version must match ELASTICSEARCH_VERSION from
        # e2e/package.json > script > "test:k8sV2" or "test:k8sV2NoBuild"
        image: elasticsearch:7.9.3
        ports:
        - containerPort: 9200
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: discovery.type
          value: single-node
---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  labels:
    app.kubernetes.io/name: elasticsearch
spec:
  selector:
      app.kubernetes.io/name: elasticsearch
      app.kubernetes.io/component: master
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30200  # the external port teraslice can be accessed on
  type: NodePort
