kind: Cluster
name: k8s-env
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.28.12@sha256:fa0e48b1e83bb8688a5724aa7eebffbd6337abd7909ad089a2700bf08c30c6ea
  extraPortMappings:
  # teraslice port mapping needs to be at index 0 in this array
  - containerPort: 30678 # Map internal teraslice service to host port
    hostPort: 5678
  - containerPort: 30200 # Map internal elasticsearch service to host port
    hostPort: 9200
  - containerPort: 30210 # Map internal opensearch service to host port
    hostPort: 9210
  - containerPort: 30092 # Map internal kafka service to host port
    hostPort: 9092
  - containerPort: 30094 # Map external kafka service to host port
    hostPort: 9094
  - containerPort: 30900 # Map internal minio service to host port
    hostPort: 9000
  - containerPort: 30901 # Map internal minio-ui service to host port
    hostPort: 9001
  extraMounts:
  - hostPath: ./e2e/autoload
    containerPath: /autoload
  - hostPath: ./e2e/helm/utility/data
    containerPath: /data
