apiVersion: apps/v1
kind: Deployment
metadata:
  name: teraslice-master
  labels:
      app.kubernetes.io/name: teraslice
      app.kubernetes.io/component: master
spec:
  replicas: 1
  selector:
      matchLabels:
          app.kubernetes.io/name: teraslice
          app.kubernetes.io/component: master
  template:
    metadata:
      labels:
        app.kubernetes.io/name: teraslice
        app.kubernetes.io/component: master
        app.kubernetes.io/instance: k8se2e
    spec:
      containers:
      - name: teraslice-master
        image: teraslice-workspace:e2e
        ports:
        - containerPort: 5678
        volumeMounts:
          - mountPath: /app/config  # defines the directory
            name: config
      volumes:
        - name: config
          configMap:
            name: teraslice-master
            items:
              - key: teraslice.yaml
                path: teraslice.yaml  # the filename that the configMap gets written to, inside the matching mountPath
      imagePullSecrets:
        - name: docker-tera1-secret
