apiVersion: apps/v1
kind: Deployment
metadata:
  name: teraslice-master
  labels:
    app.kubernetes.io/name: teraslice
    app.kubernetes.io/component: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: teraslice
      app.kubernetes.io/component: master
  template:
    metadata:
      labels:
        app.kubernetes.io/name: teraslice
        app.kubernetes.io/component: master
        app.kubernetes.io/instance: k8s-e2e
    spec:
      containers:
      - name: teraslice-master
        image: "" # set dynamically w/ scripts/src/helpers/config.ts NODE_VERSION: teraslice-workspace:e2e-nodev${NODE_VERSION}
        ports:
        - containerPort: 5678
        volumeMounts:
          - mountPath: /app/config # defines the directory
            name: config
          - mountPath: /app/autoload # defines the directory
            name: autoload
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: teraslice-master
            items:
              - key: teraslice.yaml
                path: teraslice.yaml # the filename that the configMap gets written to, inside the matching mountPath
        - name: autoload
          hostPath:
            path: /autoload
            type: Directory
      imagePullSecrets:
        - name: docker-tera1-secret
      serviceAccountName: master-service-account
