kind: Service
apiVersion: v1
metadata:
  name: teraslice-master
  labels:
    app.kubernetes.io/name: teraslice
spec:
  selector:
      app.kubernetes.io/name: teraslice
      app.kubernetes.io/component: master
  ports:
  - port: 5678
    targetPort: 5678
    nodePort: 30678  # the external port teraslice can be accessed on
  type: NodePort
