apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
      app.kubernetes.io/name: minio
      app.kubernetes.io/component: master
spec:
  replicas: 1
  selector:
      matchLabels:
          app.kubernetes.io/name: minio
          app.kubernetes.io/component: master
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
        app.kubernetes.io/component: master
    spec:
      containers:
      - name: minio
        image: ''
        args:
        - minio server /data --console-address :9001
        ports:
        - containerPort: 9000
        - containerPort: 9001
        command:
        - /bin/bash
        - -c
        env:
          - name: MINIO_ROOT_USER
            value: minioadmin
          - name: MINIO_ROOT_PASSWORD
            value: minioadmin
---
kind: Service
apiVersion: v1
metadata:
  name: minio
  labels:
    app.kubernetes.io/name: minio
spec:
  type: NodePort
  selector:
      app.kubernetes.io/name: minio
      app.kubernetes.io/component: master
  ports:
  - port: 9000
    name: minio
    targetPort: 9000
    nodePort: 30900
  - port: 9001
    name: minio1
    targetPort: 9001
    nodePort: 30901
