kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: teraslice-master-ts-dev1
  namespace: ts-dev1
subjects:
  - kind: ServiceAccount
    name: master-service-account
    namespace: ts-dev1
roleRef:
  kind: Role
  name: teraslice-master-role-ts-dev1
  apiGroup: "rbac.authorization.k8s.io"
