kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: teraslice-all-ts-dev1
  namespace: ts-dev1
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ts-dev1
roleRef:
  kind: Role
  name: teraslice-all-ts-dev1
  apiGroup: "rbac.authorization.k8s.io"