/** Declaration file generated by dts-gen */

export function calculate(now: any, offsetVal: any, unit: any): any;

export function evaluate(expression: any, now?: any, roundUp?: any, timeZone?: any, useTimeZoneForRounding?: any): any;

export function parse(expression: any, now?: any, roundUp?: any, timeZone?: any, useTimeZoneForRounding?: any): any;

export function parseTime(s: any, timeZone: any): any;

export function roundDate(now: any, unit: any, roundUp: any, timeZone: any, useTimeZoneForRounding: any): any;
