kind: Cluster
name: k8s-e2e
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings: []
  # Leaving this commented out as a reference instead if removing.
  # `image`, `hostPort` and `containerPort` are dynamically set here:
  # https://github.com/terascope/teraslice/blob/master/packages/scripts/src/helpers/kind.ts
  #
  # image: kindest/node:<K8S_VERSION>@sha256:<some_hash>
  #
  # teraslice port mapping needs to be at index 0 in this array
  # - containerPort: 30678 # Map internal teraslice service to host port
  #   hostPort: 45678
  # - containerPort: 30210 # Map internal opensearch service to host port
  #   hostPort: 49210
  # - containerPort: 30092 # Map internal kafka service to host port
  #   hostPort: 49092
  # - containerPort: 30094 # Map external kafka service to host port
  #   hostPort: 49094
  # - containerPort: 30379 # Map internal valkey service to host port
  #   hostPort: 46379
  # - containerPort: 30900 # Map internal minio service to host port
  #   hostPort: 49000
  # - containerPort: 30901 # Map internal minio-ui service to host port
  #   hostPort: 49001

  extraMounts:
  # hostPaths are relative to node process.cwd() - e2e directory in this case
  - hostPath: ./autoload
    containerPath: /autoload
  - hostPath: ./logs
    containerPath: /mnt/logs  
    # recovery-spec needs visibility into assets from jest environment   
  - hostPath: ./assets
    containerPath: /e2e-assets