'use strict';

const {
    TEST_INDEX_PREFIX = 'teratest_',
    ELASTICSEARCH_HOST = 'http://localhost:9200',
    ELASTICSEARCH_API_VERSION = '6.5',
    ELASTICSEARCH_VERSION = '6.8.6',
    OPENSEARCH_USER = 'admin',
    OPENSEARCH_PASSWORD = 'admin',
    OPENSEARCH_VERSION = '1.3.0',
    RESTRAINED_OPENSEARCH_PORT = process.env.RESTRAINED_OPENSEARCH_PORT || '49206',
    RESTRAINED_OPENSEARCH_HOST = `http://${OPENSEARCH_USER}:${OPENSEARCH_PASSWORD}@http://localhost:${RESTRAINED_OPENSEARCH_PORT}`,
} = process.env;

module.exports = {
    TEST_INDEX_PREFIX,
    ELASTICSEARCH_HOST,
    ELASTICSEARCH_API_VERSION,
    ELASTICSEARCH_VERSION,
    RESTRAINED_OPENSEARCH_HOST,
    OPENSEARCH_VERSION
};
