# baseCmd="earl"
baseCmd="node ./index.js"

declare -a cmds=(
    "${baseCmd}"
    "${baseCmd} aliases"
    "${baseCmd} aliases add"
    "${baseCmd} aliases list"
    "${baseCmd} aliases remove"
    "${baseCmd} aliases update"
    "${baseCmd} assets"
    "${baseCmd} assets build"
    "${baseCmd} assets delete"
    "${baseCmd} assets deploy"
    "${baseCmd} assets registry"
    "${baseCmd} assets list"
    "${baseCmd} controllers"
    "${baseCmd} controllers list"
    "${baseCmd} controllers stats"
    "${baseCmd} ex"
    "${baseCmd} ex errors"
    "${baseCmd} ex list"
    "${baseCmd} ex status"
    "${baseCmd} ex stop"
    "${baseCmd} jobs"
    "${baseCmd} jobs errors"
    "${baseCmd} jobs list"
    "${baseCmd} jobs pause"
    "${baseCmd} jobs recover"
    "${baseCmd} jobs restart"
    "${baseCmd} jobs resume"
    "${baseCmd} jobs run"
    "${baseCmd} jobs save"
    "${baseCmd} jobs status"
    "${baseCmd} jobs stop"
    "${baseCmd} jobs view"
    "${baseCmd} jobs workers"
    "${baseCmd} nodes"
    "${baseCmd} nodes list"
    "${baseCmd} tjm"
    "${baseCmd} tjm errors"
    "${baseCmd} tjm init"
    "${baseCmd} tjm register"
    "${baseCmd} tjm reset"
    "${baseCmd} tjm run"
    "${baseCmd} tjm start"
    "${baseCmd} tjm stop"
    "${baseCmd} tjm update"
    "${baseCmd} tjm view"
    "${baseCmd} workers"
    "${baseCmd} workers list"
)

for cmd in "${cmds[@]}"
do
    echo "# Output for ${cmd} --help"
    echo
    echo '```'
    ${cmd} --help
    echo '```'
    echo
done
