packages:
  - ./

allowBuilds:
  # Used by a package within @docusaurus/core
  core-js: true

blockExoticSubdeps: true

minimumReleaseAge: 1440 # 1 day

trustPolicy: no-downgrade

trustPolicyExclude:
  - 'semver@6.3.1' # false positive - maintainer change
  - 'detect-port@1.6.1' #  false positive - republished without provenance

overrides:
  webpack: 5.105.1
