kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: teraslice-master-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "teraslice.master.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "teraslice.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: teraslice-master-role-{{ .Release.Name }}
  apiGroup: "rbac.authorization.k8s.io"
