{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "teraslice.fullname" . }}
  labels:
    {{- include "teraslice.master.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: /cluster/stats
      port: api
      interval: {{ .Values.serviceMonitor.interval }}
      metricRelabelings:
        {{- toYaml .Values.serviceMonitor.metricRelabelings | nindent 8 }}
      relabelings:
        {{- toYaml .Values.serviceMonitor.relabelings | nindent 8 }}
    {{- if or .Values.terafoundation.prom_metrics_enabled .Values.exporter.enabled }}
    - path: /metrics
      port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
      metricRelabelings:
        {{- toYaml .Values.serviceMonitor.metricRelabelings | nindent 8 }}
      relabelings:
        {{- toYaml .Values.serviceMonitor.relabelings | nindent 8 }}
    {{- end }}
  jobLabel: app.kubernetes.io/instance
  selector:
    matchLabels:
      {{- include "teraslice.master.selectorLabels" . | nindent 6 }}
{{- end }}
