import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { z } from 'zod';
import { customAlphabet } from 'nanoid';
import semver from 'semver';
import { toBoolean } from '@terascope/core-utils';
import { getRootInfo } from '@terascope/scripts';
import { Logger } from '@terascope/types';

type BoolStrings = 'true' | 'false';
const boolean: BoolStrings[] = ['true', 'false'];
const logLevels: Logger.LogLevelString[] = ['trace', 'debug', 'info', 'warn', 'error', 'fatal'];

const E2EEnvSchema = z.object({
    ASSET_STORAGE_CONNECTION: z.string().optional(),
    ASSET_STORAGE_CONNECTION_TYPE: z.string().optional(),
    CERT_PATH: z.string(),
    DEBUG_LOG_LEVEL: z.enum(logLevels).optional(),
    ENCRYPT_KAFKA: z.enum(boolean).optional(),
    ENCRYPT_MINIO: z.enum(boolean).optional(),
    ENCRYPT_OPENSEARCH: z.enum(boolean).optional(),
    FILE_LOGGING: z.enum(boolean),
    GENERATE_ONLY: z.string().optional(),
    HOST_IP: z.string(),
    KAFKA_BROKER: z.string(),
    KAFKA_PORT: z.string().optional(),
    KEEP_OPEN: z.enum(boolean).optional(),
    KIND_CLUSTER: z.string(),
    MINIO_ACCESS_KEY: z.string().optional(),
    MINIO_HOST: z.string().optional(),
    MINIO_SECRET_KEY: z.string().optional(),
    NODE_VERSION: z.string(),
    OPENSEARCH_PASSWORD: z.string().optional(),
    OPENSEARCH_USER: z.string().optional(),
    OPENSEARCH_VERSION: z.string().optional(),
    SEARCH_TEST_HOST: z.string(),
    TERASLICE_PORT: z.string(),
    TEST_INDEX_PREFIX: z.string(),
    TEST_OPENSEARCH: z.enum(boolean).optional(),
    TEST_PLATFORM: z.string(),
    USE_DEV_ASSETS: z.enum(boolean).optional(),
    USE_HELMFILE: z.enum(boolean),
});

const envConfig = E2EEnvSchema.parse(process.env);

const filePath = fileURLToPath(new URL(import.meta.url));
/*
from the execution of the test from how its called internally and externally it deviates
"some/path/terascope/teraslice/e2e/test/config.ts
            vs
"some/path/terascope/teraslice/e2e/dist/test/config.js
so we search for the e2e part and slice that off to make both work
*/
const pathLength = filePath.lastIndexOf('e2e') + 3;

const BASE_PATH = filePath.slice(0, pathLength);

// The number of teraslice-worker instances (see the docker-compose.yml)
const DEFAULT_WORKERS = 2;

// Check current teraslice for pre release tag. Use dev assets if present.
const terasliceVersion = semver.coerce(getRootInfo().version, { includePrerelease: true });

const USE_DEV_ASSETS = envConfig.USE_DEV_ASSETS
    ? toBoolean(envConfig.USE_DEV_ASSETS) || false
    : terasliceVersion?.prerelease
        ? terasliceVersion.prerelease.length > 0
        : false;

function newId(prefix?: string, lowerCase = false, length = 15) {
    let characters = '0123456789abcdefghijklmnopqrstuvwxyz';

    if (!lowerCase) {
        characters += 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    }

    const id = customAlphabet(characters, length)();

    if (prefix) {
        return `${prefix}-${id}`;
    }

    return id;
}

export const config = {
    ...envConfig,
    // Location of cached teraslice assets generated by e2e/scripts/downloadAssets.js
    ASSETS_PATH: path.join(BASE_PATH, '../assets'),
    ASSET_BUNDLES_PATH: '/tmp/teraslice_assets',
    AUTOLOAD_PATH: path.join(BASE_PATH, 'autoload'),
    BASE_PATH,
    // the uniq cluster name
    CLUSTER_NAME: newId(`${envConfig.TEST_INDEX_PREFIX}teracluster`, true, 2),
    CONFIG_PATH: path.join(BASE_PATH, '.config'),
    // The teraslice-master + the number of teraslice-worker instances (see the docker-compose.yml)
    DEFAULT_NODES: DEFAULT_WORKERS + 1,
    DEFAULT_WORKERS,
    EXAMPLE_INDEX_PREFIX: `${envConfig.TEST_INDEX_PREFIX}example`,
    EXAMPLE_INDEX_SIZES: [100, 1000],
    LOG_PATH: path.join(BASE_PATH, 'logs/teraslice.log'),
    newId,
    ROOT_CERT_PATH: path.join(envConfig.CERT_PATH, 'CAs/rootCA.pem'),
    SPEC_INDEX_PREFIX: `${envConfig.TEST_INDEX_PREFIX}spec`,
    // The number of workers per number (see the process-master.yaml and process-worker.yaml)
    TEST_HOST: envConfig.SEARCH_TEST_HOST,
    USE_DEV_ASSETS,
    WORKERS_PER_NODE: 8,
};
