/** Declaration file generated by dts-gen */

/**
 * `datemath-parser` is CommonJS and assigns `module.exports` to the result of an
 * IIFE, so its named exports are not statically detectable. Node therefore exposes
 * only the default export to ESM importers, which is what this declares.
 */
declare const parser: {
    calculate(now: any, offsetVal: any, unit: any): any;

    evaluate(expression: any, now?: any, roundUp?: any, timeZone?: any, useTimeZoneForRounding?: any): any;

    parse(expression: any, now?: any, roundUp?: any, timeZone?: any, useTimeZoneForRounding?: any): any;

    parseTime(s: any, timeZone: any): any;

    roundDate(now: any, unit: any, roundUp: any, timeZone: any, useTimeZoneForRounding: any): any;
};

export default parser;
