name: Publish
# NPM Trusted Publishing allows only a single triggering workflow

on:
  pull_request:
    branches:
      - master
      - 'release/teraslice-v*'
    types:
      - closed
    paths-ignore:
      - 'helm/helm-repo-site/index.yaml'
  release:
    types: [published]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  call-publish-master:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'master'
    uses: ./.github/workflows/publish-master.yml
    secrets: inherit

  call-publish-dev:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && startsWith(github.base_ref, 'release/teraslice-v')
    uses: ./.github/workflows/publish-dev.yml
    secrets: inherit

  call-publish-tag:
    if: github.event_name == 'release'
    uses: ./.github/workflows/publish-tag.yml
    secrets: inherit
