name: Publish Assets
run-name: Publish assets to npm

on:
  release:
    types: [published]

jobs:
  build-release:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Register npm token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version:  18.16.0
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install and build packages
        run: yarn setup
        env:
          YARN_SETUP_ARGS: "--prod=false --silent"

      - name: Build documentation
        run: ./scripts/publish-documentation.sh

      - name: Publish to npm
        run: yarn ts-scripts publish -t tag npm

      - name: Publish to docker
        run: yarn ts-scripts publish -t tag docker

