# name: Publish Assets
# run-name: Publish assets to npm

# on:
#   release:
#     types: [published]

# jobs:
#   build-linux-node-14:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out code
#         uses: actions/checkout@v3

#       - name: Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 14.21.3
#           cache: 'yarn'

#       - name: Install teraslice-cli
#         run: yarn global add teraslice-cli

#       - name: Install and build packages
#         run: yarn setup

#       - name: Build asset
#         run: teraslice-cli assets build

#       - name: Upload built asset
#         uses: actions/upload-artifact@v3
#         with:
#           name: kafka-node-14
#           path: 'build/*'

#   build-linux-node-16:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out code
#         uses: actions/checkout@v3

#       - name: Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 16.19.1
#           cache: 'yarn'

#       - name: Install teraslice-cli
#         run: yarn global add teraslice-cli

#       - name: Install and build packages
#         run: yarn setup

#       - name: Build asset
#         run: teraslice-cli assets build

#       - name: Upload built asset
#         uses: actions/upload-artifact@v3
#         with:
#           name: kafka-node-16
#           path: 'build/*'

#   build-linux-node-18:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out code
#         uses: actions/checkout@v3

#       - name: Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18.16.0
#           cache: 'yarn'

#       - name: Install teraslice-cli
#         run: yarn global add teraslice-cli

#       - name: Install and build packages
#         run: yarn setup

#       - name: Build asset
#         run: teraslice-cli assets build

#       - name: Upload built asset
#         uses: actions/upload-artifact@v3
#         with:
#           name: kafka-node-18
#           path: 'build/*'

#   release-assets:
#     runs-on: ubuntu-latest
#     needs: [build-linux-node-14, build-linux-node-16, build-linux-node-18]
#     env:
#       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#     steps:
#       - name: Register npm token
#         run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

#       - uses: actions/setup-node@v3
#         with:
#           node-version: 18.16.0
#           registry-url: 'https://registry.npmjs.org'

#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Install and build packages
#         run: yarn setup

#       - name: Download all build versions
#         uses: actions/download-artifact@v3
#         with:
#           path: ./build

#       - name: Publish to npm
#         run: 'yarn publish:changed'

#       - name: Release
#         uses: softprops/action-gh-release@v1
#         with:
#           files: build/**/*.zip
