name: Teraslice CI Tests
run-name: Teraslice Tests
# this will technically run again on merge to master, should limit it
on:
  pull_request:
    branches: [ master ]

jobs:
  verify-build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 14.21.3
        cache: 'yarn'

    - name: Install and build packages
      run: yarn setup
      env:
        YARN_SETUP_ARGS: "--prod=false --silent"

    - name: Lint codebase
      run: yarn lint

    - name: Sync codebase
      run: yarn sync --verify

  linux-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.21.3, 16.19.1, 18.16.0]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install and build packages
        run: yarn setup
        env:
          YARN_SETUP_ARGS: "--prod=false --silent"

      - name: Test
        run: TZ=utc yarn --silent test -- --suite unit --

  teraslice-elasticsearch-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.21.3, 16.19.1, 18.16.0]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      # we login to docker to avoid docker pull limit rates
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install and build packages
        run: yarn setup
        env:
          YARN_SETUP_ARGS: "--prod=false --silent"

      - name: Test elasticsearch 6
        run: yarn --silent test --suite elasticsearch --elasticsearch-version 6.8.6 --elasticsearch-api-version 6.5

      - name: Test elasticsearch 7
        run: yarn --silent test --suite elasticsearch --elasticsearch-version 7.2.1 --elasticsearch-api-version 7.0 --report-coverage false

  elasticsearch-store-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.21.3, 16.19.1, 18.16.0]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      # we login to docker to avoid docker pull limit rates
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install and build packages
        run: yarn setup
        env:
          YARN_SETUP_ARGS: "--prod=false --silent"

      - name: Test elasticsearch 6
        run: yarn --silent test  --report-coverage false
        working-directory: ./packages/elasticsearch-store

      - name: Test elasticsearch 7
        run: yarn --silent test:7 --report-coverage false
        working-directory: ./packages/elasticsearch-store

      - name: Test opensearch 1.3
        run: yarn --silent test:opensearch --report-coverage false
        working-directory: ./packages/elasticsearch-store

  # This is for backwards compatability, should be removed in the future
  elasticsearch-store-legacy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.21.3
          cache: 'yarn'

      # we login to docker to avoid docker pull limit rates
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install and build packages
        run: yarn setup
        env:
          YARN_SETUP_ARGS: "--prod=false --silent"

      - name: Test
        run: yarn --silent test:legacy  --report-coverage false
        working-directory: ./packages/elasticsearch-store

  elasticsearch-api-tests:
    needs: [verify-build,  linux-unit-tests, elasticsearch-store-legacy, elasticsearch-store-tests, teraslice-elasticsearch-tests]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.21.3, 16.19.1, 18.16.0]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      # we login to docker to avoid docker pull limit rates
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install and build packages
        run: yarn setup
        env:
          YARN_SETUP_ARGS: "--prod=false --silent"

      - name: Test elasticsearch 6
        run: yarn --silent test  --report-coverage false
        working-directory: ./packages/elasticsearch-api

      - name: Test elasticsearch 7
        run: yarn --silent test:7 --report-coverage false
        working-directory: ./packages/elasticsearch-api

      - name: Test opensearch
        run: yarn --silent test:opensearch --report-coverage false
        working-directory: ./packages/elasticsearch-api


  # This is for backwards compatability, should be removed in the future
  elasticsearch-api-legacy:
    needs: [verify-build,  linux-unit-tests, elasticsearch-store-legacy, elasticsearch-store-tests, teraslice-elasticsearch-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.21.3
          cache: 'yarn'

      # we login to docker to avoid docker pull limit rates
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install and build packages
        run: yarn setup
        env:
          YARN_SETUP_ARGS: "--prod=false --silent"

      - name: Test
        run: yarn --silent test:legacy  --report-coverage false
        working-directory: ./packages/elasticsearch-api

  e2e-tests:
    needs: [elasticsearch-api-tests]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.21.3, 16.19.1, 18.16.0]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      # we login to docker to avoid docker pull limit rates
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install and build packages
        run: yarn setup
        env:
          YARN_SETUP_ARGS: "--prod=false --silent"

      - name: Test
        run: yarn --silent test
        working-directory: ./e2e
